# palette = true
# no_color = false
# no_bar_delimiter = false
# no_title = false
# no_ascii = false
# no_box = true
# bar = true
# random_color = false
# random_sep_color = false
# short_uptime = false
# short_shell = true
small_ascii = true
no_separator = true
no_title = true
hide = [ "Machine", "LocalIP", "Host", "Kernel", "ProcessorUsage", "Packages" ]
